kind: Service
apiVersion: v1
metadata:
  name: api-practice
  namespace: local-dev
  labels:
    app: api-practice
    app.kubernetes.io/component: api-practice
    app.kubernetes.io/instance: api-practice
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deploymentconfig: api-practice
